[package]
name = "indexer_science"
version = "0.1.0"
edition = "2021"

[dependencies]
harana_common = { package = "common", path = "../../common" }
harana_document = { package = "document", path = "../../document" }
harana_indexer_core = { package = "indexer_core", path = "../core" }
harana_io = { package = "io", path = "../../io" }

c3dio = "0.4.0"
sp3 = "1.0.8"

[[bench]]
name = "benchmark_science"
harness = false
