[package]
name = "tantivy"
version = "0.1.0"
edition = "2021"

[dependencies]
harana_common = { package = "common", path = "../common" }
harana_io = { package = "io", path = "../io" }

async-channel = { version = "1", features = [] }
bincode = "1"
compose = { git = "https://github.com/lnx-search/compose.git", tag = "0.1.0" }
crc32fast = "1.3.2"
deunicode = "1.4.0"
directories = "5"
sled = "0.34"
walkdir = "2.4.0"
zip = "0.6.6"
