INSERT INTO search_categories (title, name, enabled, position) VALUES ("Application", "application", 1, 0);
INSERT INTO search_categories (title, name, enabled, position) VALUES ("Archive", "archive", 1, 1);
INSERT INTO search_categories (title, name, enabled, position) VALUES ("Audio", "audio", 1, 2);
INSERT INTO search_categories (title, name, enabled, position) VALUES ("Book", "book", 1, 3);
INSERT INTO search_categories (title, name, enabled, position) VALUES ("Calendar", "calendar", 1, 4);
INSERT INTO search_categories (title, name, enabled, position) VALUES ("Certificate", "certificate", 1, 5);
INSERT INTO search_categories (title, name, enabled, position) VALUES ("Code", "code", 1, 6);
INSERT INTO search_categories (title, name, enabled, position) VALUES ("Code Artifact", "code-artifact", 1, 7);
INSERT INTO search_categories (title, name, enabled, position) VALUES ("Data", "data", 1, 8);
INSERT INTO search_categories (title, name, enabled, position) VALUES ("Database", "database", 1, 9);
INSERT INTO search_categories (title, name, enabled, position) VALUES ("Disk Image", "disk-image", 1, 10);
INSERT INTO search_categories (title, name, enabled, position) VALUES ("Document", "document", 1, 11);
INSERT INTO search_categories (title, name, enabled, position) VALUES ("Email", "email", 1, 12);
INSERT INTO search_categories (title, name, enabled, position) VALUES ("Folder", "folder", 1, 13);
INSERT INTO search_categories (title, name, enabled, position) VALUES ("Font", "font", 1, 14);
INSERT INTO search_categories (title, name, enabled, position) VALUES ("Game", "game", 1, 15);
INSERT INTO search_categories (title, name, enabled, position) VALUES ("Graphics", "graphics", 1, 16);
INSERT INTO search_categories (title, name, enabled, position) VALUES ("Hardware", "hardware", 1, 17);
INSERT INTO search_categories (title, name, enabled, position) VALUES ("Image", "image", 1, 18);
INSERT INTO search_categories (title, name, enabled, position) VALUES ("Map", "map", 1, 19);
INSERT INTO search_categories (title, name, enabled, position) VALUES ("Other", "other", 1, 20);
INSERT INTO search_categories (title, name, enabled, position) VALUES ("Science", "science", 1, 21);
INSERT INTO search_categories (title, name, enabled, position) VALUES ("Screenshot", "screenshot", 1, 22);
INSERT INTO search_categories (title, name, enabled, position) VALUES ("Video", "video", 1, 23);