INSERT OR IGNORE INTO settings (key, value) VALUES ("appearance_always_center_window", "true");
INSERT OR IGNORE INTO settings (key, value) VALUES ("appearance_font_size", "14");
INSERT OR IGNORE INTO settings (key, value) VALUES ("appearance_language", "English");
INSERT OR IGNORE INTO settings (key, value) VALUES ("appearance_shortcut_key", "Command+Space");
INSERT OR IGNORE INTO settings (key, value) VALUES ("appearance_theme", "Light");
INSERT OR IGNORE INTO settings (key, value) VALUES ("privacy_share_error_reports", "true");
INSERT OR IGNORE INTO settings (key, value) VALUES ("privacy_share_usage_data", "true");
INSERT OR IGNORE INTO settings (key, value) VALUES ("startup_show_in_dock", "true");
INSERT OR IGNORE INTO settings (key, value) VALUES ("startup_start_at_login", "true");