[package]
name = "thumbnailer_heif"
version = "0.1.0"
edition = "2021"

[dependencies]
harana_common = { package = "common", path = "../../common" }
harana_document = { package = "document", path = "../../document" }
harana_io = { package = "io", path = "../../io" }
harana_search_core = { package = "search_core", path = "../../search/core" }
harana_thumbnailer_core = { package = "thumbnailer_core", path = "../core" }

libheif-rs = { git = "https://github.com/harana-oss/libheif-rs" }