[package]
name = "rpc_ws"
version = "0.1.0"
edition = "2021"

[dependencies]
harana_rpc_core = { package = "rpc_core", path = "../core" }
harana_rpc_utils = { package = "rpc_utils", path = "../utils" }

ws = { git = "https://github.com/harana-oss/ws-rs.git" }