[package]
name = "indexer_game"
version = "0.1.0"
edition = "2021"

[dependencies]
harana_common = { package = "common", path = "../../common" }
harana_document = { package = "document", path = "../../document" }
harana_indexer_core = { package = "indexer_core", path = "../core" }
harana_io = { package = "io", path = "../../io" }

ffmml = "0.1.2"
rofl-parser = "0.1.26"
unpak = "1.0.5"

[[bench]]
name = "benchmark_game"
harness = false
