/*
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActionsAddCustomLabelsToSelfHostedRunnerForOrgRequest {
    /// The names of the custom labels to add to the runner.
    #[serde(rename = "labels")]
    pub labels: Vec<String>,
}

impl ActionsAddCustomLabelsToSelfHostedRunnerForOrgRequest {
    pub fn new(labels: Vec<String>) -> ActionsAddCustomLabelsToSelfHostedRunnerForOrgRequest {
        ActionsAddCustomLabelsToSelfHostedRunnerForOrgRequest {
            labels,
        }
    }
}

