/*
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActionsSetGithubActionsPermissionsRepositoryRequest {
    /// Whether GitHub Actions is enabled on the repository.
    #[serde(rename = "enabled")]
    pub enabled: bool,
    #[serde(rename = "allowed_actions", skip_serializing_if = "Option::is_none")]
    pub allowed_actions: Option<models::AllowedActions>,
}

impl ActionsSetGithubActionsPermissionsRepositoryRequest {
    pub fn new(enabled: bool) -> ActionsSetGithubActionsPermissionsRepositoryRequest {
        ActionsSetGithubActionsPermissionsRepositoryRequest {
            enabled,
            allowed_actions: None,
        }
    }
}

