/*
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActionsListGithubHostedRunnersInGroupForOrg200Response {
    #[serde(rename = "total_count")]
    pub total_count: f64,
    #[serde(rename = "runners")]
    pub runners: Vec<models::ActionsHostedRunner>,
}

impl ActionsListGithubHostedRunnersInGroupForOrg200Response {
    pub fn new(total_count: f64, runners: Vec<models::ActionsHostedRunner>) -> ActionsListGithubHostedRunnersInGroupForOrg200Response {
        ActionsListGithubHostedRunnersInGroupForOrg200Response {
            total_count,
            runners,
        }
    }
}

