/*
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActionsSetDefaultWorkflowPermissions {
    #[serde(rename = "default_workflow_permissions", skip_serializing_if = "Option::is_none")]
    pub default_workflow_permissions: Option<models::ActionsDefaultWorkflowPermissions>,
    /// Whether GitHub Actions can approve pull requests. Enabling this can be a security risk.
    #[serde(rename = "can_approve_pull_request_reviews", skip_serializing_if = "Option::is_none")]
    pub can_approve_pull_request_reviews: Option<bool>,
}

impl ActionsSetDefaultWorkflowPermissions {
    pub fn new() -> ActionsSetDefaultWorkflowPermissions {
        ActionsSetDefaultWorkflowPermissions {
            default_workflow_permissions: None,
            can_approve_pull_request_reviews: None,
        }
    }
}

