/*
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BillingUsageReport {
    #[serde(rename = "usageItems", skip_serializing_if = "Option::is_none")]
    pub usage_items: Option<Vec<models::BillingUsageReportUsageItemsInner>>,
}

impl BillingUsageReport {
    pub fn new() -> BillingUsageReport {
        BillingUsageReport {
            usage_items: None,
        }
    }
}

