/*
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CodespacesListInOrganization200Response {
    #[serde(rename = "total_count")]
    pub total_count: i32,
    #[serde(rename = "codespaces")]
    pub codespaces: Vec<models::Codespace>,
}

impl CodespacesListInOrganization200Response {
    pub fn new(total_count: i32, codespaces: Vec<models::Codespace>) -> CodespacesListInOrganization200Response {
        CodespacesListInOrganization200Response {
            total_count,
            codespaces,
        }
    }
}

