/*
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CodeSecurityCreateConfigurationForEnterpriseRequestDependencyGraphAutosubmitActionOptions : Feature options for Automatic dependency submission
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CodeSecurityCreateConfigurationForEnterpriseRequestDependencyGraphAutosubmitActionOptions {
    /// Whether to use runners labeled with 'dependency-submission' or standard GitHub runners.
    #[serde(rename = "labeled_runners", skip_serializing_if = "Option::is_none")]
    pub labeled_runners: Option<bool>,
}

impl CodeSecurityCreateConfigurationForEnterpriseRequestDependencyGraphAutosubmitActionOptions {
    /// Feature options for Automatic dependency submission
    pub fn new() -> CodeSecurityCreateConfigurationForEnterpriseRequestDependencyGraphAutosubmitActionOptions {
        CodeSecurityCreateConfigurationForEnterpriseRequestDependencyGraphAutosubmitActionOptions {
            labeled_runners: None,
        }
    }
}

