/*
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CodeScanningAlertLocation : Describe a region within a file for the alert.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CodeScanningAlertLocation {
    #[serde(rename = "path", skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
    #[serde(rename = "start_line", skip_serializing_if = "Option::is_none")]
    pub start_line: Option<i32>,
    #[serde(rename = "end_line", skip_serializing_if = "Option::is_none")]
    pub end_line: Option<i32>,
    #[serde(rename = "start_column", skip_serializing_if = "Option::is_none")]
    pub start_column: Option<i32>,
    #[serde(rename = "end_column", skip_serializing_if = "Option::is_none")]
    pub end_column: Option<i32>,
}

impl CodeScanningAlertLocation {
    /// Describe a region within a file for the alert.
    pub fn new() -> CodeScanningAlertLocation {
        CodeScanningAlertLocation {
            path: None,
            start_line: None,
            end_line: None,
            start_column: None,
            end_column: None,
        }
    }
}

