/*
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ContentTraffic : Content Traffic
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContentTraffic {
    #[serde(rename = "path")]
    pub path: String,
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "count")]
    pub count: i32,
    #[serde(rename = "uniques")]
    pub uniques: i32,
}

impl ContentTraffic {
    /// Content Traffic
    pub fn new(path: String, title: String, count: i32, uniques: i32) -> ContentTraffic {
        ContentTraffic {
            path,
            title,
            count,
            uniques,
        }
    }
}

