/*
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CopilotOrganizationSeatBreakdown : The breakdown of Copilot Business seats for the organization.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CopilotOrganizationSeatBreakdown {
    /// The total number of seats being billed for the organization as of the current billing cycle.
    #[serde(rename = "total", skip_serializing_if = "Option::is_none")]
    pub total: Option<i32>,
    /// Seats added during the current billing cycle.
    #[serde(rename = "added_this_cycle", skip_serializing_if = "Option::is_none")]
    pub added_this_cycle: Option<i32>,
    /// The number of seats that are pending cancellation at the end of the current billing cycle.
    #[serde(rename = "pending_cancellation", skip_serializing_if = "Option::is_none")]
    pub pending_cancellation: Option<i32>,
    /// The number of users who have been invited to receive a Copilot seat through this organization.
    #[serde(rename = "pending_invitation", skip_serializing_if = "Option::is_none")]
    pub pending_invitation: Option<i32>,
    /// The number of seats that have used Copilot during the current billing cycle.
    #[serde(rename = "active_this_cycle", skip_serializing_if = "Option::is_none")]
    pub active_this_cycle: Option<i32>,
    /// The number of seats that have not used Copilot during the current billing cycle.
    #[serde(rename = "inactive_this_cycle", skip_serializing_if = "Option::is_none")]
    pub inactive_this_cycle: Option<i32>,
}

impl CopilotOrganizationSeatBreakdown {
    /// The breakdown of Copilot Business seats for the organization.
    pub fn new() -> CopilotOrganizationSeatBreakdown {
        CopilotOrganizationSeatBreakdown {
            total: None,
            added_this_cycle: None,
            pending_cancellation: None,
            pending_invitation: None,
            active_this_cycle: None,
            inactive_this_cycle: None,
        }
    }
}

