/*
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CopilotAddCopilotSeatsForTeamsRequest {
    /// List of team names within the organization to which to grant access to GitHub Copilot.
    #[serde(rename = "selected_teams")]
    pub selected_teams: Vec<String>,
}

impl CopilotAddCopilotSeatsForTeamsRequest {
    pub fn new(selected_teams: Vec<String>) -> CopilotAddCopilotSeatsForTeamsRequest {
        CopilotAddCopilotSeatsForTeamsRequest {
            selected_teams,
        }
    }
}

