/*
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CopilotIdeChatEditorsInnerModelsInner {
    /// Name of the model used for Copilot Chat. If the default model is used will appear as 'default'.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Indicates whether a model is custom or default.
    #[serde(rename = "is_custom_model", skip_serializing_if = "Option::is_none")]
    pub is_custom_model: Option<bool>,
    /// The training date for the custom model.
    #[serde(rename = "custom_model_training_date", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub custom_model_training_date: Option<Option<String>>,
    /// The number of users who prompted Copilot Chat in the given editor and model.
    #[serde(rename = "total_engaged_users", skip_serializing_if = "Option::is_none")]
    pub total_engaged_users: Option<i32>,
    /// The total number of chats initiated by users in the given editor and model.
    #[serde(rename = "total_chats", skip_serializing_if = "Option::is_none")]
    pub total_chats: Option<i32>,
    /// The number of times users accepted a code suggestion from Copilot Chat using the 'Insert Code' UI element, for the given editor.
    #[serde(rename = "total_chat_insertion_events", skip_serializing_if = "Option::is_none")]
    pub total_chat_insertion_events: Option<i32>,
    /// The number of times users copied a code suggestion from Copilot Chat using the keyboard, or the 'Copy' UI element, for the given editor.
    #[serde(rename = "total_chat_copy_events", skip_serializing_if = "Option::is_none")]
    pub total_chat_copy_events: Option<i32>,
}

impl CopilotIdeChatEditorsInnerModelsInner {
    pub fn new() -> CopilotIdeChatEditorsInnerModelsInner {
        CopilotIdeChatEditorsInnerModelsInner {
            name: None,
            is_custom_model: None,
            custom_model_training_date: None,
            total_engaged_users: None,
            total_chats: None,
            total_chat_insertion_events: None,
            total_chat_copy_events: None,
        }
    }
}

