/*
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DependabotAlertSecurityAdvisoryIdentifiersInner : An advisory identifier.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DependabotAlertSecurityAdvisoryIdentifiersInner {
    /// The type of advisory identifier.
    #[serde(rename = "type")]
    pub r#type: Type,
    /// The value of the advisory identifer.
    #[serde(rename = "value")]
    pub value: String,
}

impl DependabotAlertSecurityAdvisoryIdentifiersInner {
    /// An advisory identifier.
    pub fn new(r#type: Type, value: String) -> DependabotAlertSecurityAdvisoryIdentifiersInner {
        DependabotAlertSecurityAdvisoryIdentifiersInner {
            r#type,
            value,
        }
    }
}
/// The type of advisory identifier.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "CVE")]
    Cve,
    #[serde(rename = "GHSA")]
    Ghsa,
}

impl Default for Type {
    fn default() -> Type {
        Self::Cve
    }
}

