/*
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FeedLinks {
    #[serde(rename = "timeline")]
    pub timeline: Box<models::LinkWithType>,
    #[serde(rename = "user")]
    pub user: Box<models::LinkWithType>,
    #[serde(rename = "security_advisories", skip_serializing_if = "Option::is_none")]
    pub security_advisories: Option<Box<models::LinkWithType>>,
    #[serde(rename = "current_user", skip_serializing_if = "Option::is_none")]
    pub current_user: Option<Box<models::LinkWithType>>,
    #[serde(rename = "current_user_public", skip_serializing_if = "Option::is_none")]
    pub current_user_public: Option<Box<models::LinkWithType>>,
    #[serde(rename = "current_user_actor", skip_serializing_if = "Option::is_none")]
    pub current_user_actor: Option<Box<models::LinkWithType>>,
    #[serde(rename = "current_user_organization", skip_serializing_if = "Option::is_none")]
    pub current_user_organization: Option<Box<models::LinkWithType>>,
    #[serde(rename = "current_user_organizations", skip_serializing_if = "Option::is_none")]
    pub current_user_organizations: Option<Vec<models::LinkWithType>>,
    #[serde(rename = "repository_discussions", skip_serializing_if = "Option::is_none")]
    pub repository_discussions: Option<Box<models::LinkWithType>>,
    #[serde(rename = "repository_discussions_category", skip_serializing_if = "Option::is_none")]
    pub repository_discussions_category: Option<Box<models::LinkWithType>>,
}

impl FeedLinks {
    pub fn new(timeline: models::LinkWithType, user: models::LinkWithType) -> FeedLinks {
        FeedLinks {
            timeline: Box::new(timeline),
            user: Box::new(user),
            security_advisories: None,
            current_user: None,
            current_user_public: None,
            current_user_actor: None,
            current_user_organization: None,
            current_user_organizations: None,
            repository_discussions: None,
            repository_discussions_category: None,
        }
    }
}

