/*
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GitCreateCommitRequestAuthor : Information about the author of the commit. By default, the `author` will be the authenticated user and the current date. See the `author` and `committer` object below for details.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GitCreateCommitRequestAuthor {
    /// The name of the author (or committer) of the commit
    #[serde(rename = "name")]
    pub name: String,
    /// The email of the author (or committer) of the commit
    #[serde(rename = "email")]
    pub email: String,
    /// Indicates when this commit was authored (or committed). This is a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ`.
    #[serde(rename = "date", skip_serializing_if = "Option::is_none")]
    pub date: Option<String>,
}

impl GitCreateCommitRequestAuthor {
    /// Information about the author of the commit. By default, the `author` will be the authenticated user and the current date. See the `author` and `committer` object below for details.
    pub fn new(name: String, email: String) -> GitCreateCommitRequestAuthor {
        GitCreateCommitRequestAuthor {
            name,
            email,
            date: None,
        }
    }
}

