/*
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HostedComputeCreateNetworkConfigurationForOrgRequest {
    /// Name of the network configuration. Must be between 1 and 100 characters and may only contain upper and lowercase letters a-z, numbers 0-9, '.', '-', and '_'.
    #[serde(rename = "name")]
    pub name: String,
    /// The hosted compute service to use for the network configuration.
    #[serde(rename = "compute_service", skip_serializing_if = "Option::is_none")]
    pub compute_service: Option<ComputeService>,
    /// The identifier of the network settings to use for the network configuration. Exactly one network settings must be specified.
    #[serde(rename = "network_settings_ids")]
    pub network_settings_ids: Vec<String>,
}

impl HostedComputeCreateNetworkConfigurationForOrgRequest {
    pub fn new(name: String, network_settings_ids: Vec<String>) -> HostedComputeCreateNetworkConfigurationForOrgRequest {
        HostedComputeCreateNetworkConfigurationForOrgRequest {
            name,
            compute_service: None,
            network_settings_ids,
        }
    }
}
/// The hosted compute service to use for the network configuration.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ComputeService {
    #[serde(rename = "none")]
    None,
    #[serde(rename = "actions")]
    Actions,
}

impl Default for ComputeService {
    fn default() -> ComputeService {
        Self::None
    }
}

