/*
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IssuesUpdateCommentRequest {
    /// The contents of the comment.
    #[serde(rename = "body")]
    pub body: String,
}

impl IssuesUpdateCommentRequest {
    pub fn new(body: String) -> IssuesUpdateCommentRequest {
        IssuesUpdateCommentRequest {
            body,
        }
    }
}

