/*
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LabeledIssueEventLabel {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "color")]
    pub color: String,
}

impl LabeledIssueEventLabel {
    pub fn new(name: String, color: String) -> LabeledIssueEventLabel {
        LabeledIssueEventLabel {
            name,
            color,
        }
    }
}

