/*
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LinkWithType : Hypermedia Link with Type
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LinkWithType {
    #[serde(rename = "href")]
    pub href: String,
    #[serde(rename = "type")]
    pub r#type: String,
}

impl LinkWithType {
    /// Hypermedia Link with Type
    pub fn new(href: String, r#type: String) -> LinkWithType {
        LinkWithType {
            href,
            r#type,
        }
    }
}

