/*
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// NullableSimpleCommitCommitter : Information about the Git committer
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NullableSimpleCommitCommitter {
    /// Name of the commit's committer
    #[serde(rename = "name")]
    pub name: String,
    /// Git email address of the commit's committer
    #[serde(rename = "email")]
    pub email: String,
}

impl NullableSimpleCommitCommitter {
    /// Information about the Git committer
    pub fn new(name: String, email: String) -> NullableSimpleCommitCommitter {
        NullableSimpleCommitCommitter {
            name,
            email,
        }
    }
}

