/*
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OrgRepoCustomPropertyValues : List of custom property values for a repository
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrgRepoCustomPropertyValues {
    #[serde(rename = "repository_id")]
    pub repository_id: i32,
    #[serde(rename = "repository_name")]
    pub repository_name: String,
    #[serde(rename = "repository_full_name")]
    pub repository_full_name: String,
    /// List of custom property names and associated values
    #[serde(rename = "properties")]
    pub properties: Vec<models::CustomPropertyValue>,
}

impl OrgRepoCustomPropertyValues {
    /// List of custom property values for a repository
    pub fn new(repository_id: i32, repository_name: String, repository_full_name: String, properties: Vec<models::CustomPropertyValue>) -> OrgRepoCustomPropertyValues {
        OrgRepoCustomPropertyValues {
            repository_id,
            repository_name,
            repository_full_name,
            properties,
        }
    }
}

