/*
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PagesHealthCheckAltDomain {
    #[serde(rename = "host", skip_serializing_if = "Option::is_none")]
    pub host: Option<String>,
    #[serde(rename = "uri", skip_serializing_if = "Option::is_none")]
    pub uri: Option<String>,
    #[serde(rename = "nameservers", skip_serializing_if = "Option::is_none")]
    pub nameservers: Option<String>,
    #[serde(rename = "dns_resolves", skip_serializing_if = "Option::is_none")]
    pub dns_resolves: Option<bool>,
    #[serde(rename = "is_proxied", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub is_proxied: Option<Option<bool>>,
    #[serde(rename = "is_cloudflare_ip", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub is_cloudflare_ip: Option<Option<bool>>,
    #[serde(rename = "is_fastly_ip", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub is_fastly_ip: Option<Option<bool>>,
    #[serde(rename = "is_old_ip_address", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub is_old_ip_address: Option<Option<bool>>,
    #[serde(rename = "is_a_record", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub is_a_record: Option<Option<bool>>,
    #[serde(rename = "has_cname_record", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub has_cname_record: Option<Option<bool>>,
    #[serde(rename = "has_mx_records_present", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub has_mx_records_present: Option<Option<bool>>,
    #[serde(rename = "is_valid_domain", skip_serializing_if = "Option::is_none")]
    pub is_valid_domain: Option<bool>,
    #[serde(rename = "is_apex_domain", skip_serializing_if = "Option::is_none")]
    pub is_apex_domain: Option<bool>,
    #[serde(rename = "should_be_a_record", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub should_be_a_record: Option<Option<bool>>,
    #[serde(rename = "is_cname_to_github_user_domain", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub is_cname_to_github_user_domain: Option<Option<bool>>,
    #[serde(rename = "is_cname_to_pages_dot_github_dot_com", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub is_cname_to_pages_dot_github_dot_com: Option<Option<bool>>,
    #[serde(rename = "is_cname_to_fastly", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub is_cname_to_fastly: Option<Option<bool>>,
    #[serde(rename = "is_pointed_to_github_pages_ip", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub is_pointed_to_github_pages_ip: Option<Option<bool>>,
    #[serde(rename = "is_non_github_pages_ip_present", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub is_non_github_pages_ip_present: Option<Option<bool>>,
    #[serde(rename = "is_pages_domain", skip_serializing_if = "Option::is_none")]
    pub is_pages_domain: Option<bool>,
    #[serde(rename = "is_served_by_pages", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub is_served_by_pages: Option<Option<bool>>,
    #[serde(rename = "is_valid", skip_serializing_if = "Option::is_none")]
    pub is_valid: Option<bool>,
    #[serde(rename = "reason", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub reason: Option<Option<String>>,
    #[serde(rename = "responds_to_https", skip_serializing_if = "Option::is_none")]
    pub responds_to_https: Option<bool>,
    #[serde(rename = "enforces_https", skip_serializing_if = "Option::is_none")]
    pub enforces_https: Option<bool>,
    #[serde(rename = "https_error", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub https_error: Option<Option<String>>,
    #[serde(rename = "is_https_eligible", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub is_https_eligible: Option<Option<bool>>,
    #[serde(rename = "caa_error", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub caa_error: Option<Option<String>>,
}

impl PagesHealthCheckAltDomain {
    pub fn new() -> PagesHealthCheckAltDomain {
        PagesHealthCheckAltDomain {
            host: None,
            uri: None,
            nameservers: None,
            dns_resolves: None,
            is_proxied: None,
            is_cloudflare_ip: None,
            is_fastly_ip: None,
            is_old_ip_address: None,
            is_a_record: None,
            has_cname_record: None,
            has_mx_records_present: None,
            is_valid_domain: None,
            is_apex_domain: None,
            should_be_a_record: None,
            is_cname_to_github_user_domain: None,
            is_cname_to_pages_dot_github_dot_com: None,
            is_cname_to_fastly: None,
            is_pointed_to_github_pages_ip: None,
            is_non_github_pages_ip_present: None,
            is_pages_domain: None,
            is_served_by_pages: None,
            is_valid: None,
            reason: None,
            responds_to_https: None,
            enforces_https: None,
            https_error: None,
            is_https_eligible: None,
            caa_error: None,
        }
    }
}

