/*
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PageBuild : Page Build
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PageBuild {
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "error")]
    pub error: Box<models::PageBuildError>,
    #[serde(rename = "pusher", deserialize_with = "Option::deserialize")]
    pub pusher: Option<Box<models::NullableSimpleUser>>,
    #[serde(rename = "commit")]
    pub commit: String,
    #[serde(rename = "duration")]
    pub duration: i32,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "updated_at")]
    pub updated_at: String,
}

impl PageBuild {
    /// Page Build
    pub fn new(url: String, status: String, error: models::PageBuildError, pusher: Option<models::NullableSimpleUser>, commit: String, duration: i32, created_at: String, updated_at: String) -> PageBuild {
        PageBuild {
            url,
            status,
            error: Box::new(error),
            pusher: if let Some(x) = pusher {Some(Box::new(x))} else {None},
            commit,
            duration,
            created_at,
            updated_at,
        }
    }
}

