/*
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PorterLargeFile : Porter Large File
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PorterLargeFile {
    #[serde(rename = "ref_name")]
    pub ref_name: String,
    #[serde(rename = "path")]
    pub path: String,
    #[serde(rename = "oid")]
    pub oid: String,
    #[serde(rename = "size")]
    pub size: i32,
}

impl PorterLargeFile {
    /// Porter Large File
    pub fn new(ref_name: String, path: String, oid: String, size: i32) -> PorterLargeFile {
        PorterLargeFile {
            ref_name,
            path,
            oid,
            size,
        }
    }
}

