/*
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ProtectedBranchPullRequestReviewBypassPullRequestAllowances : Allow specific users, teams, or apps to bypass pull request requirements.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProtectedBranchPullRequestReviewBypassPullRequestAllowances {
    /// The list of users allowed to bypass pull request requirements.
    #[serde(rename = "users", skip_serializing_if = "Option::is_none")]
    pub users: Option<Vec<models::SimpleUser>>,
    /// The list of teams allowed to bypass pull request requirements.
    #[serde(rename = "teams", skip_serializing_if = "Option::is_none")]
    pub teams: Option<Vec<models::Team>>,
    /// The list of apps allowed to bypass pull request requirements.
    #[serde(rename = "apps", skip_serializing_if = "Option::is_none")]
    pub apps: Option<Vec<models::Integration>>,
}

impl ProtectedBranchPullRequestReviewBypassPullRequestAllowances {
    /// Allow specific users, teams, or apps to bypass pull request requirements.
    pub fn new() -> ProtectedBranchPullRequestReviewBypassPullRequestAllowances {
        ProtectedBranchPullRequestReviewBypassPullRequestAllowances {
            users: None,
            teams: None,
            apps: None,
        }
    }
}

