/*
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProtectedBranchEnforceAdmins {
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "enabled")]
    pub enabled: bool,
}

impl ProtectedBranchEnforceAdmins {
    pub fn new(url: String, enabled: bool) -> ProtectedBranchEnforceAdmins {
        ProtectedBranchEnforceAdmins {
            url,
            enabled,
        }
    }
}

