/*
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ReferrerTraffic : Referrer Traffic
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReferrerTraffic {
    #[serde(rename = "referrer")]
    pub referrer: String,
    #[serde(rename = "count")]
    pub count: i32,
    #[serde(rename = "uniques")]
    pub uniques: i32,
}

impl ReferrerTraffic {
    /// Referrer Traffic
    pub fn new(referrer: String, count: i32, uniques: i32) -> ReferrerTraffic {
        ReferrerTraffic {
            referrer,
            count,
            uniques,
        }
    }
}

