/*
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RepositoryRuleUpdate : Only allow users with bypass permission to update matching refs.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RepositoryRuleUpdate {
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "parameters", skip_serializing_if = "Option::is_none")]
    pub parameters: Option<Box<models::RepositoryRuleUpdateParameters>>,
}

impl RepositoryRuleUpdate {
    /// Only allow users with bypass permission to update matching refs.
    pub fn new(r#type: Type) -> RepositoryRuleUpdate {
        RepositoryRuleUpdate {
            r#type,
            parameters: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "update")]
    Update,
}

impl Default for Type {
    fn default() -> Type {
        Self::Update
    }
}

