/*
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReposUpdateBranchProtectionRequestRequiredStatusChecksChecksInner {
    /// The name of the required check
    #[serde(rename = "context")]
    pub context: String,
    /// The ID of the GitHub App that must provide this check. Omit this field to automatically select the GitHub App that has recently provided this check, or any app if it was not set by a GitHub App. Pass -1 to explicitly allow any app to set the status.
    #[serde(rename = "app_id", skip_serializing_if = "Option::is_none")]
    pub app_id: Option<i32>,
}

impl ReposUpdateBranchProtectionRequestRequiredStatusChecksChecksInner {
    pub fn new(context: String) -> ReposUpdateBranchProtectionRequestRequiredStatusChecksChecksInner {
        ReposUpdateBranchProtectionRequestRequiredStatusChecksChecksInner {
            context,
            app_id: None,
        }
    }
}

