/*
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RepositoryRuleMaxFilePathLength : Prevent commits that include file paths that exceed a specified character limit from being pushed to the commit graph.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RepositoryRuleMaxFilePathLength {
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "parameters", skip_serializing_if = "Option::is_none")]
    pub parameters: Option<Box<models::RepositoryRuleMaxFilePathLengthParameters>>,
}

impl RepositoryRuleMaxFilePathLength {
    /// Prevent commits that include file paths that exceed a specified character limit from being pushed to the commit graph.
    pub fn new(r#type: Type) -> RepositoryRuleMaxFilePathLength {
        RepositoryRuleMaxFilePathLength {
            r#type,
            parameters: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "max_file_path_length")]
    MaxFilePathLength,
}

impl Default for Type {
    fn default() -> Type {
        Self::MaxFilePathLength
    }
}

