/*
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SocialAccount : Social media account
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SocialAccount {
    #[serde(rename = "provider")]
    pub provider: String,
    #[serde(rename = "url")]
    pub url: String,
}

impl SocialAccount {
    /// Social media account
    pub fn new(provider: String, url: String) -> SocialAccount {
        SocialAccount {
            provider,
            url,
        }
    }
}

