/*
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// StarredRepository : Starred Repository
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StarredRepository {
    #[serde(rename = "starred_at")]
    pub starred_at: String,
    #[serde(rename = "repo")]
    pub repo: Box<models::Repository>,
}

impl StarredRepository {
    /// Starred Repository
    pub fn new(starred_at: String, repo: models::Repository) -> StarredRepository {
        StarredRepository {
            starred_at,
            repo: Box::new(repo),
        }
    }
}

