/*
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubIssuesSummary {
    #[serde(rename = "total")]
    pub total: i32,
    #[serde(rename = "completed")]
    pub completed: i32,
    #[serde(rename = "percent_completed")]
    pub percent_completed: i32,
}

impl SubIssuesSummary {
    pub fn new(total: i32, completed: i32, percent_completed: i32) -> SubIssuesSummary {
        SubIssuesSummary {
            total,
            completed,
            percent_completed,
        }
    }
}

