/*
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Tag : Tag
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Tag {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "commit")]
    pub commit: Box<models::ShortBranchCommit>,
    #[serde(rename = "zipball_url")]
    pub zipball_url: String,
    #[serde(rename = "tarball_url")]
    pub tarball_url: String,
    #[serde(rename = "node_id")]
    pub node_id: String,
}

impl Tag {
    /// Tag
    pub fn new(name: String, commit: models::ShortBranchCommit, zipball_url: String, tarball_url: String, node_id: String) -> Tag {
        Tag {
            name,
            commit: Box::new(commit),
            zipball_url,
            tarball_url,
            node_id,
        }
    }
}

