/*
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WebhookMemberEditedChanges : The changes to the collaborator permissions
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebhookMemberEditedChanges {
    #[serde(rename = "old_permission", skip_serializing_if = "Option::is_none")]
    pub old_permission: Option<Box<models::WebhookMemberEditedChangesOldPermission>>,
    #[serde(rename = "permission", skip_serializing_if = "Option::is_none")]
    pub permission: Option<Box<models::WebhookMemberEditedChangesPermission>>,
}

impl WebhookMemberEditedChanges {
    /// The changes to the collaborator permissions
    pub fn new() -> WebhookMemberEditedChanges {
        WebhookMemberEditedChanges {
            old_permission: None,
            permission: None,
        }
    }
}

