/*
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebhookSponsorshipEditedChanges {
    #[serde(rename = "privacy_level", skip_serializing_if = "Option::is_none")]
    pub privacy_level: Option<Box<models::WebhookSponsorshipEditedChangesPrivacyLevel>>,
}

impl WebhookSponsorshipEditedChanges {
    pub fn new() -> WebhookSponsorshipEditedChanges {
        WebhookSponsorshipEditedChanges {
            privacy_level: None,
        }
    }
}

