/*
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebhookPullRequestEditedChangesBase {
    #[serde(rename = "ref")]
    pub r#ref: Box<models::WebhookDiscussionCommentEditedChangesBody>,
    #[serde(rename = "sha")]
    pub sha: Box<models::WebhookDiscussionCommentEditedChangesBody>,
}

impl WebhookPullRequestEditedChangesBase {
    pub fn new(r#ref: models::WebhookDiscussionCommentEditedChangesBody, sha: models::WebhookDiscussionCommentEditedChangesBody) -> WebhookPullRequestEditedChangesBase {
        WebhookPullRequestEditedChangesBase {
            r#ref: Box::new(r#ref),
            sha: Box::new(sha),
        }
    }
}

