/*
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebhooksSecurityAdvisoryIdentifiersInner {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "value")]
    pub value: String,
}

impl WebhooksSecurityAdvisoryIdentifiersInner {
    pub fn new(r#type: String, value: String) -> WebhooksSecurityAdvisoryIdentifiersInner {
        WebhooksSecurityAdvisoryIdentifiersInner {
            r#type,
            value,
        }
    }
}

