/*
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WebhookProjectsV2ItemEditedChanges : The changes made to the item may involve modifications in the item's fields and draft issue body. It includes altered values for text, number, date, single select, and iteration fields, along with the GraphQL node ID of the changed field.
/// The changes made to the item may involve modifications in the item's fields and draft issue body. It includes altered values for text, number, date, single select, and iteration fields, along with the GraphQL node ID of the changed field.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum WebhookProjectsV2ItemEditedChanges {
    WebhookProjectsV2ItemEditedChangesOneOf(Box<models::WebhookProjectsV2ItemEditedChangesOneOf>),
    WebhookProjectsV2ItemEditedChangesOneOf1(Box<models::WebhookProjectsV2ItemEditedChangesOneOf1>),
}

impl Default for WebhookProjectsV2ItemEditedChanges {
    fn default() -> Self {
        Self::WebhookProjectsV2ItemEditedChangesOneOf(Default::default())
    }
}

