/*
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WebhookCheckRunRequestedActionRequestedAction : The action requested by the user.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebhookCheckRunRequestedActionRequestedAction {
    /// The integrator reference of the action requested by the user.
    #[serde(rename = "identifier", skip_serializing_if = "Option::is_none")]
    pub identifier: Option<String>,
}

impl WebhookCheckRunRequestedActionRequestedAction {
    /// The action requested by the user.
    pub fn new() -> WebhookCheckRunRequestedActionRequestedAction {
        WebhookCheckRunRequestedActionRequestedAction {
            identifier: None,
        }
    }
}

