[package]
name = "indexer_email"
version = "0.1.0"
edition = "2021"

[dependencies]
harana_common = { package = "common", path = "../../common" }
harana_document = { package = "document", path = "../../document" }
harana_indexer_core = { package = "indexer_core", path = "../core" }
harana_io = { package = "io", path = "../../io" }

eml-parser = "0.1.4"
emlx = "0.1.0"
msg_parser = "0.1.1"

[[bench]]
name = "benchmark_email"
harness = false
