[package]
name = "search_ruby"
version = "0.1.0"
edition = "2021"

[dependencies]
harana_common = { package = "common", path = "../common" }
harana_transfer = { package = "search_transfer", path = "../search/transfer" }

rutie = "0.9.0"

[lib]
crate-type = ["cdylib"]