[package]
name = "opener_noop"
version = "0.1.0"
edition = "2021"

[dependencies]
harana_common = { package = "common", path = "../../common" }
harana_opener_core = { package = "opener_core", path = "../core" }
harana_io = { package = "io", path = "../../io" }