[package]
name = "meilisearch"
version = "0.1.0"
edition = "2021"

[dependencies]
harana_common = { package = "common", path = "../common" }
flume = { git = "https://github.com/zesterer/flume", branch = "master" }
