[package]
name = "rpc_core"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
futures = { version = "0.3", optional = true }
futures-util = { version = "0.3", default-features = false, features = ["std"] }
futures-executor = { version = "0.3", optional = true }
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"

[features]
default = ["futures-executor", "futures"]
arbitrary_precision = ["serde_json/arbitrary_precision"]


