[package]
name = "rpc_core"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = { version = "0.3", optional = true }
futures-util = { version = "0.3", default-features = false, features = ["std"] }
futures-executor = { version = "0.3", optional = true }

