use harana_thumbnailer_aiff::thumbnailer_aiff::ThumbnailerAiff;
use harana_thumbnailer_avif::thumbnailer_avif::ThumbnailerAvif;
use harana_thumbnailer_bmp::thumbnailer_bmp::ThumbnailerBmp;
use harana_thumbnailer_code::thumbnailer_code::ThumbnailerCode;
use harana_thumbnailer_dds::thumbnailer_dds::ThumbnailerDds;
use harana_thumbnailer_epub::thumbnailer_epub::ThumbnailerEpub;
use harana_thumbnailer_flac::thumbnailer_flac::ThumbnailerFlac;
use harana_thumbnailer_gif::thumbnailer_gif::ThumbnailerGif;
use harana_thumbnailer_heif::thumbnailer_heif::ThumbnailerHeif;
use harana_thumbnailer_ico::thumbnailer_ico::ThumbnailerIco;
use harana_thumbnailer_ipynb::thumbnailer_ipynb::ThumbnailerIpynb;
use harana_thumbnailer_jpeg::thumbnailer_jpeg::ThumbnailerJpeg;
use harana_thumbnailer_json::thumbnailer_json::ThumbnailerJson;
use harana_thumbnailer_m4a::thumbnailer_m4a::ThumbnailerM4a;
use harana_thumbnailer_mac::thumbnailer_mac::ThumbnailerMac;
use harana_thumbnailer_md::thumbnailer_md::ThumbnailerMd;
use harana_thumbnailer_mp3::thumbnailer_mp3::ThumbnailerMp3;
use harana_thumbnailer_noop::thumbnailer_noop::ThumbnailerNoop;
use harana_thumbnailer_png::thumbnailer_png::ThumbnailerPng;
use harana_thumbnailer_pnm::thumbnailer_pnm::ThumbnailerPnm;
use harana_thumbnailer_ppm::thumbnailer_ppm::ThumbnailerPpm;
use harana_thumbnailer_psd::thumbnailer_psd::ThumbnailerPsd;
use harana_thumbnailer_qoi::thumbnailer_qoi::ThumbnailerQoi;
use harana_thumbnailer_raw::thumbnailer_raw::ThumbnailerRaw;
use harana_thumbnailer_svg::thumbnailer_svg::ThumbnailerSvg;
use harana_thumbnailer_tex::thumbnailer_tex::ThumbnailerTex;
use harana_thumbnailer_tga::thumbnailer_tga::ThumbnailerTga;
use harana_thumbnailer_three::thumbnailer_three::ThumbnailerThree;
use harana_thumbnailer_tiff::thumbnailer_tiff::ThumbnailerTiff;
use harana_thumbnailer_txt::thumbnailer_txt::ThumbnailerTxt;
// use harana_thumbnailer_video::thumbnailer_video::ThumbnailerVideo;
use harana_thumbnailer_wav::thumbnailer_wav::ThumbnailerWav;
use harana_thumbnailer_webp::thumbnailer_webp::ThumbnailerWebp;

pub static Aiff: ThumbnailerAiff = ThumbnailerAiff;
pub static Avif: ThumbnailerAvif = ThumbnailerAvif;
pub static Bmp: ThumbnailerBmp = ThumbnailerBmp;
pub static Code: ThumbnailerCode = ThumbnailerCode;
pub static Dds: ThumbnailerDds = ThumbnailerDds;
pub static Epub: ThumbnailerEpub = ThumbnailerEpub;
pub static Flac: ThumbnailerFlac = ThumbnailerFlac;
pub static Gif: ThumbnailerGif = ThumbnailerGif;
pub static Heif: ThumbnailerHeif = ThumbnailerHeif;
pub static Ico: ThumbnailerIco = ThumbnailerIco;
pub static Ipynb: ThumbnailerIpynb = ThumbnailerIpynb;
pub static Jpeg: ThumbnailerJpeg = ThumbnailerJpeg;
pub static Json: ThumbnailerJson = ThumbnailerJson;
pub static M4a: ThumbnailerM4a = ThumbnailerM4a;
pub static Mac: ThumbnailerMac = ThumbnailerMac;
pub static Md: ThumbnailerMd = ThumbnailerMd;
pub static Mp3: ThumbnailerMp3 = ThumbnailerMp3;
pub static Noop: ThumbnailerNoop = ThumbnailerNoop;
pub static Png: ThumbnailerPng = ThumbnailerPng;
pub static Pnm: ThumbnailerPnm = ThumbnailerPnm;
pub static Ppm: ThumbnailerPpm = ThumbnailerPpm;
pub static Psd: ThumbnailerPsd = ThumbnailerPsd;
pub static Qoi: ThumbnailerQoi = ThumbnailerQoi;
pub static Raw: ThumbnailerRaw = ThumbnailerRaw;
pub static Svg: ThumbnailerSvg = ThumbnailerSvg;
pub static Tex: ThumbnailerTex = ThumbnailerTex;
pub static Tga: ThumbnailerTga = ThumbnailerTga;
pub static Three: ThumbnailerThree = ThumbnailerThree;
pub static Tiff: ThumbnailerTiff = ThumbnailerTiff;
pub static Txt: ThumbnailerTxt = ThumbnailerTxt;
pub static Video: ThumbnailerNoop = ThumbnailerNoop;
pub static Wav: ThumbnailerWav = ThumbnailerWav;
pub static Webp: ThumbnailerWebp = ThumbnailerWebp;