[package]
name = "thumbnailer_three"
version = "0.1.0"
edition = "2021"

[dependencies]
harana_common = { package = "common", path = "../../common" }
harana_document = { package = "document", path = "../../document" }
harana_io = { package = "io", path = "../../io" }
harana_search_core = { package = "search_core", path = "../../search/core" }
harana_thumbnailer_core = { package = "thumbnailer_core", path = "../core" }

filament-bindings = "0.2.2"
image = "0.24.7"