[package]
name = "job"
version = "0.1.0"
edition = "2021"

[dependencies]
harana_common = { package = "common", path = "../common" }
harana_database = { package = "database", path = "../database" }

effectum = { git = "https://github.com/harana-oss/effectum.git" }
log = "0.4"
time = "0.3"
