[package]
name = "utils"
version = "0.1.0"
edition = "2021"

[dependencies]
harana_common = { package = "common", path = "../common" }

[dev-dependencies]
tokio = { version = "1", features = ["full"] }

[build-dependencies]
flate2 = "1"
