[package]
name = "thumbnailer_video"
version = "0.1.0"
edition = "2021"

[dependencies]
harana_common = { package = "common", path = "../../common" }
harana_document = { package = "document", path = "../../document" }
harana_io = { package = "io", path = "../../io" }
harana_search_core = { package = "search_core", path = "../../search/core" }
harana_thumbnailer_core = { package = "thumbnailer_core", path = "../core" }

cstr = "0.2"
#rsmpeg = { version = "0.14", features = ["ffmpeg6"] }