[package]
name = "rpc_tauri"
version = "0.1.0"
edition = "2021"

[dependencies]
harana_common = { package = "common", path = "../../common" }
harana_rpc_core = { package = "rpc_core", path = "../core" }
harana_rpc_ws = { package = "rpc_ws", path = "../ws" }

portpicker = "0.1"
serde_json = "1.0"
serde = "1.0"