[package]
name = "search_jni"
version = "0.1.0"
edition = "2021"

[dependencies]
harana_common = { package = "common", path = "../common" }
harana_transfer = { package = "search_transfer", path = "../search/transfer" }

jni = "0.21"

[lib]
crate-type = ["cdylib"]