[package]
name = "indexer_image"
version = "0.1.0"
edition = "2021"

[dependencies]
harana_common = { package = "common", path = "../../common" }
harana_document = { package = "document", path = "../../document" }
harana_indexer_core = { package = "indexer_core", path = "../core" }
harana_io = { package = "io", path = "../../io" }

libraw = { git = "https://github.com/harana-oss/libraw-rs.git" }
lrcat-extractor = "0.4.1"
psd = "0.3.5"
svg_metadata = "0.5.1"
svg = "0.17.0"

[[bench]]
name = "benchmark_image"
harness = false