[package]
name = "rpc_pubsub"
version = "0.1.0"
edition = "2021"

[dependencies]
harana_rpc_core = { package = "rpc_core", path = "../core" }

fastrand = "2"
futures = { version = "0.3", features = ["thread-pool"] }
lazy_static = "1"
log = "0.4"
parking_lot = "0.12"
serde = "1.0"

[dev-dependencies]
serde_json = "1.0"


