[package]
name = "io"
version = "0.1.0"
edition = "2021"

[dependencies]
harana_common = { package = "common", path = "../common" }

blake3 = "1.5.0"
highway = "1.1"
infer = "0.15"
serde = { version = "1.0", features = ["derive"] }
walkdir = "2.3"
zip = "0.6"