[package]
name = "search_transfer"
version = "0.1.0"
edition = "2021"

[dependencies]
harana_common = { package = "common", path = "../../common" }
harana_document = { package = "document", path = "../../document" }
harana_search_extensions = { package = "search_extensions", path = "../extensions" }
harana_search_index = { package = "search_index", path = "../index" }
harana_tantivy = { package = "tantivy", path = "../../tantivy" }