[package]
name = "indexer_code"
version = "0.1.0"
edition = "2021"

[dependencies]
harana_common = { package = "common", path = "../../common" }
harana_indexer_core = { package = "indexer_core", path = "../core" }

comment-parser = "0.1.0"

[[bench]]
name = "benchmark_code"
harness = false