name: Generate Rust Clients from OpenAPI Specs

on:
  # Run manually
  workflow_dispatch:
  
  # Run on a schedule (daily at midnight UTC)
  schedule:
    - cron: '0 0 * * *'

jobs:
  generate-clients:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        client:
          - name: github-api-client
            spec_url: https://raw.githubusercontent.com/github/rest-api-description/main/descriptions/api.github.com/api.github.com.json
            output_dir: clients/github
          # Add more clients as needed:
          # - name: another-api-client
          #   spec_url: https://example.com/api-spec.json
          #   output_dir: clients/another
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Fetch OpenAPI spec
        run: |
          mkdir -p tmp
          curl -o tmp/openapi-spec.json "${{ matrix.client.spec_url }}"
      
      - name: Download OpenAPI Generator CLI
        run: |
          wget https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/6.6.0/openapi-generator-cli-6.6.0.jar -O openapi-generator-cli.jar
      
      - name: Generate Rust client
        run: |
          CLIENT_NAME="${{ matrix.client.name }}"
          OUTPUT_DIR="${{ matrix.client.output_dir }}"
          
          # Create the output directory if it doesn't exist
          mkdir -p "$OUTPUT_DIR"
          
          # Run the OpenAPI Generator
          java -jar openapi-generator-cli.jar generate \
            -i tmp/openapi-spec.json \
            -g rust \
            -o "$OUTPUT_DIR" \
            --additional-properties packageName=$CLIENT_NAME
      
      - name: Create branch
        id: create-branch
        run: |
          BRANCH_NAME="feat/update-rust-client-${{ matrix.client.name }}-$(date +'%Y-%m-%d')"
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git checkout -b $BRANCH_NAME
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT
      
      - name: Commit changes
        run: |
          git add "${{ matrix.client.output_dir }}/"
          # Only commit if there are changes
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
            exit 0
          else
            git commit -m "Update Rust client for ${{ matrix.client.name }} from OpenAPI spec"
            git push origin ${{ steps.create-branch.outputs.branch_name }}
          fi
      
      - name: Create Pull Request
        if: success() && env.PR_NEEDED
        uses: peter-evans/create-pull-request@v5
        env:
          PR_NEEDED: ${{ contains(github.event.head_commit.message, 'Update Rust client') }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Update Rust client for ${{ matrix.client.name }}"
          body: |
            This PR updates the Rust client for ${{ matrix.client.name }} based on the latest OpenAPI specification.
            
            - Generated from: ${{ matrix.client.spec_url }}
            - Generated on: $(date +'%Y-%m-%d')
            
            This update was automatically generated by the OpenAPI Generator GitHub Action.
          branch: ${{ steps.create-branch.outputs.branch_name }}
          base: main
          draft: false