name: Generate Rust Clients from OpenAPI Specs

on:
  # Run manually
  workflow_dispatch:
  
  # Run on a schedule (daily at midnight UTC)
  schedule:
    - cron: '0 0 * * *'

env:
  OPENAPI_VERSION: ${{ github.event.inputs.openapi_version || '7.12.0' }}
  SWAGGER_VERSION: ${{ github.event.inputs.swagger_version || '3.0.65' }}

jobs:
  generate-clients:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        client:
          - name: github-api-client
            spec_url: https://raw.githubusercontent.com/github/rest-api-description/main/descriptions/api.github.com/api.github.com.json
            output_dir: clients/github
            generator: openapi
          # Add more clients as needed:
          # - name: another-api-client
          #   spec_url: https://example.com/api-spec.json
          #   output_dir: clients/another
          #   generator: swagger
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Fetch OpenAPI spec
        run: |
          mkdir -p tmp
          curl -o tmp/openapi-spec.json "${{ matrix.client.spec_url }}"
      
      - name: Download Generator CLIs
        run: |
          # Download OpenAPI Generator CLI
          wget https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/${{ env.OPENAPI_VERSION }}/openapi-generator-cli-${{ env.OPENAPI_VERSION }}.jar -O openapi-generator-cli.jar
          
          # Download Swagger Codegen CLI
          wget https://repo1.maven.org/maven2/io/swagger/codegen/v3/swagger-codegen-cli/${{ env.SWAGGER_VERSION }}/swagger-codegen-cli-${{ env.SWAGGER_VERSION }}.jar -O swagger-codegen-cli.jar
      
      - name: Generate Rust client
        run: |
          CLIENT_NAME="${{ matrix.client.name }}"
          OUTPUT_DIR="${{ matrix.client.output_dir }}"
          GENERATOR="${{ matrix.client.generator }}"
          
          # Create the output directory if it doesn't exist
          mkdir -p "$OUTPUT_DIR"
          echo "Creating client in directory: $OUTPUT_DIR"
          
          if [ "$GENERATOR" == "openapi" ]; then
            echo "Using OpenAPI Generator for $CLIENT_NAME"
            # Run the OpenAPI Generator
            java -jar openapi-generator-cli.jar generate \
              -i tmp/openapi-spec.json \
              -g rust \
              -o "$OUTPUT_DIR" \
              --additional-properties packageName=$CLIENT_NAME
          elif [ "$GENERATOR" == "swagger" ]; then
            echo "Using Swagger Codegen for $CLIENT_NAME"
            # Run the Swagger Codegen
            java -jar swagger-codegen-cli.jar generate \
              -i tmp/openapi-spec.json \
              -l rust \
              -o "$OUTPUT_DIR" \
              -D packageName=$CLIENT_NAME
          else
            echo "Error: Unknown generator type: $GENERATOR"
            exit 1
          fi
          
          # Verify files were generated
          echo "Files generated in $OUTPUT_DIR:"
          ls -la "$OUTPUT_DIR"
          if [ "$(ls -A $OUTPUT_DIR)" ]; then
            echo "Files were successfully generated"
          else
            echo "Error: No files were generated in $OUTPUT_DIR"
            exit 1
          fi
      
          rm -f *.jar
          rm -rf tmp

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Update Rust client for ${{ matrix.client.name }}"
          commit-message: "Update Rust client for ${{ matrix.client.name }}"
          body: |
            This PR updates the Rust client for ${{ matrix.client.name }} based on the latest OpenAPI specification.
            
            - Generated from: ${{ matrix.client.spec_url }}
            - Generated using: ${{ matrix.client.generator == 'openapi' && 'OpenAPI Generator' || 'Swagger Codegen' }}
            - Generator version: ${{ matrix.client.generator == 'openapi' && env.OPENAPI_VERSION || env.SWAGGER_VERSION }}
            - Generated on: $(date +'%Y-%m-%d')
            
            This update was automatically generated by the API Client Generator GitHub Action.
          base: main
          draft: false