name: Generate Rust Clients from OpenAPI Specs

on:
  # Run manually
  workflow_dispatch:
  
  # Run on a schedule (daily at midnight UTC)
  schedule:
    - cron: '0 0 * * *'

env:
  OPENAPI_VERSION: ${{ github.event.inputs.openapi_version || '7.12.0' }}
  SWAGGER_VERSION: ${{ github.event.inputs.swagger_version || '3.0.65' }}

jobs:
  generate-clients:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        client:
          - name: github-api-client
            spec_url: https://raw.githubusercontent.com/github/rest-api-description/main/descriptions/api.github.com/api.github.com.json
            output_dir: clients/github
            generator: openapi
          # Add more clients as needed:
          # - name: another-api-client
          #   spec_url: https://example.com/api-spec.json
          #   output_dir: clients/another
          #   generator: swagger
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Fetch OpenAPI spec
        run: |
          mkdir -p tmp
          curl -o tmp/openapi-spec.json "${{ matrix.client.spec_url }}"
      
      - name: Download Generator CLIs
        run: |
          # Download OpenAPI Generator CLI
          wget https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/${{ env.OPENAPI_VERSION }}/openapi-generator-cli-${{ env.OPENAPI_VERSION }}.jar -O openapi-generator-cli.jar
          
          # Download Swagger Codegen CLI
          wget https://repo1.maven.org/maven2/io/swagger/codegen/v3/swagger-codegen-cli/${{ env.SWAGGER_VERSION }}/swagger-codegen-cli-${{ env.SWAGGER_VERSION }}.jar -O swagger-codegen-cli.jar
      
      - name: Generate Rust client
        run: |
          CLIENT_NAME="${{ matrix.client.name }}"
          OUTPUT_DIR="${{ matrix.client.output_dir }}"
          GENERATOR="${{ matrix.client.generator }}"
          
          # Create the output directory if it doesn't exist
          mkdir -p "$OUTPUT_DIR"
          echo "Creating client in directory: $OUTPUT_DIR"
          
          if [ "$GENERATOR" == "openapi" ]; then
            echo "Using OpenAPI Generator for $CLIENT_NAME"
            # Run the OpenAPI Generator
            java -jar openapi-generator-cli.jar generate \
              -i tmp/openapi-spec.json \
              -g rust \
              -o "$OUTPUT_DIR" \
              --additional-properties packageName=$CLIENT_NAME
          elif [ "$GENERATOR" == "swagger" ]; then
            echo "Using Swagger Codegen for $CLIENT_NAME"
            # Run the Swagger Codegen
            java -jar swagger-codegen-cli.jar generate \
              -i tmp/openapi-spec.json \
              -l rust \
              -o "$OUTPUT_DIR" \
              -D packageName=$CLIENT_NAME
          else
            echo "Error: Unknown generator type: $GENERATOR"
            exit 1
          fi
          
          # Verify files were generated
          echo "Files generated in $OUTPUT_DIR:"
          ls -la "$OUTPUT_DIR"
          if [ "$(ls -A $OUTPUT_DIR)" ]; then
            echo "Files were successfully generated"
          else
            echo "Error: No files were generated in $OUTPUT_DIR"
            exit 1
          fi
      
      - name: Create branch
        id: create-branch
        run: |
          # Generate a random string for the branch name
          RANDOM_ID=$(openssl rand -hex 4)
          BRANCH_NAME="feat/update-rust-client-${{ matrix.client.name }}-$RANDOM_ID"
          
          echo "Using branch name: $BRANCH_NAME"
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git checkout -b $BRANCH_NAME
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT
      
      - name: Commit changes
        id: commit
        run: |
          # First, clean up any artifacts from the generation process
          rm -f *.jar
          rm -rf tmp
          
          # Check if we have changes in the output directory
          FULL_OUTPUT_DIR="${{ matrix.client.output_dir }}"
          echo "Checking for changes in directory: $FULL_OUTPUT_DIR"
          
          if [ ! -d "$FULL_OUTPUT_DIR" ]; then
            echo "Error: Output directory doesn't exist: $FULL_OUTPUT_DIR"
            exit 1
          fi
          
          # List files to be added
          echo "Files to be added to git:"
          git status "$FULL_OUTPUT_DIR/"
          
          # Stage changes
          git add "$FULL_OUTPUT_DIR/"
          
          # Check if there are staged changes
          STAGED_CHANGES=$(git diff --cached --name-only | wc -l)
          echo "Number of staged files: $STAGED_CHANGES"
          
          if [ $STAGED_CHANGES -gt 0 ]; then
            echo "Changes detected, creating commit"
            git commit -m "Update Rust client for ${{ matrix.client.name }} using ${{ matrix.client.generator }} generator"
            echo "commit_created=true" >> $GITHUB_OUTPUT
          else
            echo "No changes to commit after staging. Here's the git status:"
            git status
            
            # Force create an empty commit for testing purposes
            echo "Creating an empty commit to continue with workflow testing"
            touch "$FULL_OUTPUT_DIR/.gitkeep"
            git add "$FULL_OUTPUT_DIR/.gitkeep"
            git commit -m "Add .gitkeep to test PR creation for ${{ matrix.client.name }}"
            echo "commit_created=true" >> $GITHUB_OUTPUT
          fi
      
      - name: Push changes
        if: steps.commit.outputs.commit_created == 'true'
        run: |
          BRANCH_NAME="${{ steps.create-branch.outputs.branch_name }}"
          echo "Pushing changes to branch $BRANCH_NAME"
          
          # Show what we're about to push
          echo "Commits to be pushed:"
          git log origin/main..$BRANCH_NAME --oneline
          
          # Push with more verbose output
          git push -u origin $BRANCH_NAME --verbose
          
          # Verify the push was successful
          echo "Verifying push succeeded:"
          git branch -vv | grep $BRANCH_NAME

      - name: Create Pull Request
        if: steps.commit.outputs.commit_created == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Update Rust client for ${{ matrix.client.name }}"
          body: |
            This PR updates the Rust client for ${{ matrix.client.name }} based on the latest OpenAPI specification.
            
            - Generated from: ${{ matrix.client.spec_url }}
            - Generated using: ${{ matrix.client.generator == 'openapi' && 'OpenAPI Generator' || 'Swagger Codegen' }}
            - Generator version: ${{ matrix.client.generator == 'openapi' && env.OPENAPI_VERSION || env.SWAGGER_VERSION }}
            - Generated on: $(date +'%Y-%m-%d')
            - Branch: ${{ steps.create-branch.outputs.branch_name }}
            
            This update was automatically generated by the API Client Generator GitHub Action.
          branch: ${{ steps.create-branch.outputs.branch_name }}
          base: main
          draft: false